name: update-po-to-md

on: [push]
jobs:
  update-po-to-md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: po2md readme.md --pofiles readme.po --quiet --save readmekr.md
